name:                scientific-calculator
version:             0.1.0.0
github:              "Daoortor/fp-2024-cub-fall"
license:             BSD-3-Clause
author:              "David Dashevskii"
maintainer:          "david.dshvsk@gmail.com"
copyright:           "© 2024 David Dashevskii"

extra-source-files:
  - README.md
  - CHANGELOG.md
  - stack.yaml

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Math

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README

dependencies:
  - base >= 4.7 && < 5
  - containers
  - parsec
  - transformers
  - criterion
  - hedgehog
  - random

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints
  - -threaded
  - -rtsopts
  - -with-rtsopts=-N

library:
  source-dirs: src

executables:
  scientific-calculator-exe:
    main:                Main.hs
    source-dirs:         app
    dependencies:
      - scientific-calculator

tests:
  scientific-calculator-test:
    main:                Spec.hs
    source-dirs:
      - test
      - common
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - scientific-calculator
      - tasty
      - tasty-hunit
      - tasty-hedgehog

benchmarks:
  performance:
    main:
      Main.hs
    source-dirs:
      - benchmark
      - common
    dependencies:
      - scientific-calculator
      - criterion
      - random