name:                spell-checker
version:             0.1.0.0
github:              "githubuser/spell-checker"
license:             BSD-3-Clause
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2024 Author name here"

extra-source-files:
- README.md
- CHANGELOG.md

description:         Please see the README on GitHub at <https://github.com/githubuser/spell-checker#readme>

dependencies:
  - base >= 4.7 && < 5
  - text
  - containers
  - array

ghc-options:
  - -Wall
  - -Wcompat
  - -Widentities
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wmissing-export-lists
  - -Wmissing-home-modules
  - -Wpartial-fields
  - -Wredundant-constraints

library:
  source-dirs: src

executables:
  spell-checker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - spell-checker

tests:
  spell-checker-test:
    main: Spec.hs
    source-dirs: test
    dependencies:
      - base >= 4.7 && < 5
      - hspec
      - text
      - containers
      - spell-checker
