name: Stack tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Set up GHC 9.6.6
      uses: haskell-actions/setup@v2
      with:
        ghc-version: '9.6.6'
        enable-stack: true
        stack-version: 'latest'
    - name: test
      run: |
        response=$(runhaskell Main.hs)
        if [[ $response == "Done" ]]; then
          echo "Output is Done"
        else
          echo "Output is:"
          echo $response
          exit 1
        fi
      shell: bash

